export const ActionTypes = {
  //READING
  GET_READING_FILL_IN_THE_BLANKS: "mock-data/GET_READING_FILL_IN_THE_BLANKS",
  GET_READING_REORDER_PARAGRAPH: "mock-data/GET_READING_REORDER_PARAGRAPH",
  GET_READING_MULTIPLE_ANSWERS: "mock-data/GET_READING_MULTIPLE_ANSWERS",
  GET_READING_SINGLE_ANSWER: "mock-data/GET_READING_SINGLE_ANSWERS",
  GET_READING_FILL_IN_THE_BLANKS_DROP_DOWN: "mock-data/GET_READING_FILL_IN_THE_BLANKS_DROP_DOWN",

  //LISTENING
  GET_LISTENING_SELECT_MISSING_WORD: "mock-data/GET_LISTENING_SELECT_MISSING_WORD",
  GET_LISTENING_MULTIPLE_ANSWERS: "mock-data/GET_LISTENING_MULTIPLE_ANSWERS",
  GET_LISTENING_HIGHLIGHT_CORRECT_SUMMARY: "mock-data/GET_LISTENING_HIGHLIGHT_CORRECT_SUMMARY",
  GET_LISTENING_WRITE_FROM_DICTATION: "mock-data/GET_LISTENING_WRITE_FROM_DICTATION",
  GET_LISTENING_HIGHLIGHT_INCORRECT_WORDS: "mock-data/GET_LISTENING_HIGHLIGHT_INCORRECT_WORDS",
  GET_LISTENING_SUMMARIZE_SPOKEN_TEXT: "mock-data/GET_LISTENING_SUMMARIZE_SPOKEN_TEXT",
  GET_LISTENING_SINGLE_ANSWER: "mock-data/GET_LISTENING_SINGLE_ANSWER",
  GET_LISTENING_FILL_IN_THE_BLANKS: "mock-data/GET_LISTENING_FILL_IN_THE_BLANKS",

  //WRITING
  GET_WRITING_SUMMARIZE_WRITTEN_TEXT: "mock-data/GET_WRITING_SUMMARIZE_WRITTEN_TEXT",
  GET_WRITING_WRITE_ESSAY: "mock-data/GET_WRITING_WRITE_ESSAY",

  //SPEAKING
  GET_SPEAKING_READ_ALOUD: "mock-data/GET_SPEAKING_READ_ALOUD",
  GET_SPEAKING_RETELL_LECTURE: "mock-data/GET_SPEAKING_RETELL_LECTURE",
  GET_SPEAKING_REPEAT_SENTENCE: "mock-data/GET_SPEAKING_REPEAT_SENTENCE",
  GET_SPEAKING_DESCRIBE_IMAGE: "mock-data/GET_SPEAKING_DESCRIBE_IMAGE",
  GET_SPEAKING_ANSWER_SHORT_QUESTION: "mock-data/GET_SPEAKING_ANSWER_SHORT_QUESTION",
};

export default ActionTypes;
